import * as T from './vendor/three.module.min.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
const $=id=>document.getElementById(id),view=$('viewport');
let config,renderer,scene,camera,controls,model,selectedHelper,scheduled=false;
const pins=[],pointer=new T.Vector2(),ray=new T.Raycaster();
const views={all:{p:[-5,24,-19],t:[12,0,4]},top:{p:[12.5,34,5.01],t:[12.5,0,5]},zone1:{p:[-5,9,-3],t:[2.8,.35,5.8]},zone2:{p:[31,8,-2],t:[23,.3,5.5]},passage:{p:[24,4,-3.5],t:[12.5,.3,1.05]}};
function showFeature(key){const f=config.features[key];if(!f)return;$('feature-select').value=key;const out=$('feature-details');out.replaceChildren();let n=document.createElement('h2');n.textContent=f.title;out.append(n);n=document.createElement('span');n.className='confidence';n.textContent=f.confidence;out.append(n);for(const [title,value,cl]of [['看到的',f.observation,''],['模型中的假设',f.assumption,'assumption'],['如何核实',f.resolve,''],['依据',f.sources.join(' · '),'source']]){const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.className=cl;p.textContent=value;out.append(h,p);}if(model){if(selectedHelper){scene.remove(selectedHelper);selectedHelper.geometry.dispose();selectedHelper.material.dispose();selectedHelper=null;}if(['bed1','bed2','drain','arch'].includes(key)){const g=model.children.find(o=>o.userData.feature===key);if(g){selectedHelper=new T.BoxHelper(g,0xad752c);scene.add(selectedHelper);}}invalidate();}}
function invalidate(){if(!scheduled){scheduled=true;requestAnimationFrame(render);}}
function render(){scheduled=false;if(!renderer)return;const changed=controls.update();renderer.render(scene,camera);for(const {el,pos} of pins){const p=pos.clone().project(camera),front=new T.Vector3().subVectors(pos,camera.position).dot(camera.getWorldDirection(new T.Vector3()))>0;el.style.left=(p.x*.5+.5)*view.clientWidth+'px';el.style.top=(-p.y*.5+.5)*view.clientHeight+'px';el.hidden=!$('annotations').checked||!front||Math.abs(p.x)>1||Math.abs(p.y)>1||p.z>1;}if(changed)invalidate();}
function setView(name){const v=views[name];camera.position.set(...v.p);controls.target.set(...v.t);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));invalidate();}
function resize(){if(!renderer)return;const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();invalidate();}
async function start(){
 const response=await fetch('./site-config.json');if(!response.ok)throw Error('Configuration unavailable');config=await response.json();
 for(const [key,f]of Object.entries(config.features)){const o=document.createElement('option');o.value=key;o.textContent=f.title;$('feature-select').append(o);}showFeature('zone1');$('feature-select').addEventListener('change',e=>showFeature(e.target.value));
 renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.shadowMap.enabled=false;renderer.shadowMap.type=T.PCFSoftShadowMap;
 renderer.domElement.setAttribute('aria-label','可旋转的现状庭院三维草模；也可使用右侧构件列表查看信息');renderer.domElement.setAttribute('tabindex','0');view.prepend(renderer.domElement);
 scene=new T.Scene();scene.background=new T.Color('#e9eeea');camera=new T.PerspectiveCamera(43,1,.1,200);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=2;controls.maxDistance=75;controls.maxPolarAngle=Math.PI*.485;controls.screenSpacePanning=true;controls.addEventListener('change',invalidate);controls.listenToKeyEvents(renderer.domElement);
 scene.add(new T.HemisphereLight(0xffffff,0x737363,2.5));const sun=new T.DirectionalLight(0xfff5dd,2.5);sun.position.set(-5,25,-4);sun.target.position.set(12,0,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:1,far:70});sun.shadow.bias=-.0005;sun.shadow.normalBias=.03;scene.add(sun,sun.target);
 const gltf=await new GLTFLoader().loadAsync('./models/existing-site.glb');model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(model);model.getObjectByName('Architecture_Upper_Proxy').visible=false;
 // Dashed rectangle is the disputed 25 x 10 m envelope, not a surveyed boundary.
 const a=config.dimensions.envelopeLength,b=config.dimensions.envelopeWidth;const pts=[[0,.09,0],[a,.09,0],[a,.09,b],[0,.09,b],[0,.09,0]].map(p=>new T.Vector3(...p));const outline=new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineDashedMaterial({color:0xac772f,dashSize:.23,gapSize:.15}));outline.computeLineDistances();scene.add(outline);
 for(const [key,text,pos]of [['zone1','01 种植池院',[2.7,.3,5]],['zone2','02 裸土院',[23,.2,4.4]],['passage','03 侧通道',[12.5,.5,.95]],['bed1','P1',[2.7,.9,1.07]],['bed2','P2',[2.7,.9,2.63]]]){const el=document.createElement('button');el.className='pin';el.textContent=text;el.setAttribute('aria-label','核对'+text);el.addEventListener('click',()=>showFeature(key));$('labels').append(el);pins.push({el,pos:new T.Vector3(...pos)});}
 let down;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(model,true).find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});if(hit){let o=hit.object;while(o&&!o.userData.feature)o=o.parent;if(o)showFeature(o.userData.feature);}});
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('reset').addEventListener('click',()=>setView('all'));
 $('full-building').addEventListener('change',e=>{model.getObjectByName('Architecture_Upper_Proxy').visible=e.target.checked;invalidate();});$('vegetation').addEventListener('change',e=>{model.getObjectByName('Existing_Vegetation_Abstract_Cover_Only').visible=e.target.checked;invalidate();});$('annotations').addEventListener('change',e=>{outline.visible=e.target.checked;invalidate();});$('shadows').addEventListener('change',e=>{renderer.shadowMap.enabled=e.target.checked;scene.traverse(o=>{if(o.material)o.material.needsUpdate=true;});invalidate();});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('failure').hidden=false;});new ResizeObserver(resize).observe(view);setView('all');resize();$('loading').hidden=true;
}
start().catch(error=>{console.error(error);$('loading').hidden=true;$('failure').hidden=false;});
