import * as T from './vendor/three.module.min.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
const $=id=>document.getElementById(id),view=$('viewport');
let config,plants,layouts,renderer,scene,camera,controls,model,selection,scheduled=false,request=0,choice='B',year=3;
const pins=[],pointer=new T.Vector2(),ray=new T.Raycaster(),loader=new GLTFLoader();
const views={all:{p:[-4,23,-20],t:[12.5,0,4.5]},top:{p:[12.5,34,5.01],t:[12.5,0,5]},zone1:{p:[-5,9,-2],t:[3.5,.3,5]},zone2:{p:[30,9,-2],t:[21,.3,5]},passage:{p:[19,4,-3.5],t:[12,.3,1]}};
const summary={existing:['清洁现状','已移除临时盆、袋、工具和菜架；保留双池、铺装、围栏、可见管线与既有轻拱架。'],A:['A · 双池的平行秩序','两个池只种低矮重复花带，不在未知土深中放大树。池间约0.48 m仅作维护缝；通行经池端与原有灰路。'],B:['B · 林缘与开敞空间','保留靠围栏 P1，拆内侧 P2，约5.2 m²池基区域局部补砖。北院形成常绿背景，南院保留约9.7 m²小草坪。'],C:['C · 连续地栽与环路','拆除两池及之间少量砖面，获得约14 m²连通地栽区。南院取消草坪，以地被岛和环路组织空间；施工与初期除草最多。']};
function invalidate(){if(!scheduled){scheduled=true;requestAnimationFrame(render);}}
function render(){scheduled=false;if(!renderer)return;const changed=controls.update();renderer.render(scene,camera);for(const {el,pos,key}of pins){const p=pos.clone().project(camera),front=pos.clone().sub(camera.position).dot(camera.getWorldDirection(new T.Vector3()))>0;el.style.left=(p.x*.5+.5)*view.clientWidth+'px';el.style.top=(-p.y*.5+.5)*view.clientHeight+'px';el.hidden=!$('annotations').checked||!front||Math.abs(p.x)>1||Math.abs(p.y)>1||p.z>1||(key==='bed1'&&choice==='C')||(key==='bed2'&&!['A','existing'].includes(choice));}if(changed)invalidate();}
function resize(){if(!renderer)return;renderer.setSize(view.clientWidth,view.clientHeight,false);camera.aspect=view.clientWidth/view.clientHeight;camera.updateProjectionMatrix();invalidate();}
function setView(name){const v=views[name];camera.position.set(...v.p);controls.target.set(...v.t);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));invalidate();}
function dispose(root){if(!root)return;const geometries=new Set(),materials=new Set();root.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
function clearSelection(){if(selection){selection.removeFromParent();selection.geometry.dispose();selection.material.dispose();selection=null;}}
function part(title,value,cl=''){const h=document.createElement('h3'),p=document.createElement('p');h.textContent=title;p.textContent=value;p.className=cl;$('feature-details').append(h,p);}
function showFeature(key){$('feature-select').value=key;const out=$('feature-details');out.replaceChildren();clearSelection();const cohort=choice!=='existing'?layouts[choice].groups.find(g=>g.id===key):null;
 if(cohort){const p=plants[cohort.species],h=document.createElement('h2');h.textContent=p.name;out.append(h);const latin=document.createElement('p');latin.className='botanical';latin.textContent=p.botanical;out.append(latin);part(`${key} · ${cohort.quantity} 株`,`建议中心距 ${p.spacing} m；第${year}年示意高 ${p.sizes[year][0]} m、幅 ${p.sizes[year][1]} m。`);part('成熟体量 / 管理体量',p.mature);part('花期与光照',p.flower+'。'+p.light);part('浇水',p.water);part('养护',p.care);if(cohort.note)part('本组落位',cohort.note,'assumption');const a=document.createElement('a');a.href=p.source;a.target='_blank';a.rel='noopener';a.textContent='植物资料来源 ↗';a.className='source-link';out.append(a);
  let object;model?.traverse(o=>{if(o.userData.plantGroup===key)object=o;});if(object){const box=new T.Box3();object.updateWorldMatrix(true,true);object.traverse(o=>{if(!o.isMesh)return;let a=o;while(a&&a!==object){if(!a.visible||a.scale.lengthSq()===0)return;a=a.parent;}o.geometry.computeBoundingBox();box.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));});if(!box.isEmpty()){selection=new T.Box3Helper(box,0xaa7836);scene.add(selection);}}
 }else if(key==='turf'){const h=document.createElement('h2');h.textContent='结缕草小草坪';out.append(h);part('植物',plants.ZJ.botanical);part('面积',`${layouts[choice]?.quantities.ZJ??0} m²；施工损耗不在模型净面积内。`);part('冬季',plants.ZJ.care);part('光照与替代',plants.ZJ.light+'。若日照不足，按0.4 m中心距改用阔叶山麦冬，取消割草任务。');part('水分',plants.ZJ.water);
 }else if(key==='newpaths'){const h=document.createElement('h2');h.textContent='新增连接通路';out.append(h);part('净宽目标','北院连接约1.2 m；南院A/B约1.2 m，C环路约1.15 m。连续、稳固、防滑；不是新增大露台。');part('落地核实','先核实门槛、格栅标高与土基，再确定灰色小规格铺材、找坡及排水衔接。');
 }else{const f=config.features[key]??config.features.zone1,h=document.createElement('h2');h.textContent=f.title;out.append(h);part('现场证据',f.observation);part('尺寸与假设',f.assumption,'assumption');part('施工前补测',f.resolve);part('影像依据',f.sources.join(' · '),'source');}invalidate();}
function fillSelect(){const select=$('feature-select');select.replaceChildren();if(choice!=='existing'){const group=document.createElement('optgroup');group.label='本方案植物组';for(const g of layouts[choice].groups)group.append(new Option(`${g.id} · ${plants[g.species].name} · ${g.quantity}株`,g.id));if(layouts[choice].quantities.ZJ)group.append(new Option('ZJ · 结缕草小草坪','turf'));select.append(group);}const fixed=document.createElement('optgroup');fixed.label='现状与构件';for(const [k,f]of Object.entries(config.features))fixed.append(new Option(f.title,k));if(choice!=='existing')fixed.append(new Option('新增连接通路','newpaths'));select.append(fixed);showFeature(choice==='existing'?'zone1':'N10');}
function season(){if(!model)return;const s=$('season').value;model.traverse(o=>{if(o.userData.flowerSeasons){const active=o.userData.flowerSeasons.includes(s);o.visible=active;o.scale.setScalar(active?1:0);}if(o.userData.leafType)o.visible=s!=='winter'||o.userData.leafType==='evergreen';if(o.userData.seasonalTurf)o.traverse(m=>{if(m.isMesh)m.material.color.set(s==='winter'?'#b3a77c':plants.ZJ.color);});});model.updateMatrixWorld(true);clearSelection();invalidate();}
async function loadModel(){const id=++request,key=choice,file=key==='existing'?'existing-site.glb':key==='B'&&year===3?'garden.glb':`design-${key}-year${year}.glb`;$('loading').hidden=false;$('loading').textContent='正在载入'+(key==='existing'?'清洁现状…':`方案 ${key} · 第${year}年…`);$('failure').hidden=true;document.querySelectorAll('[data-design]').forEach(b=>b.classList.toggle('active',b.dataset.design===key));$('year').disabled=$('season').disabled=key==='existing';
 try{const gltf=await loader.loadAsync('./models/'+file+'?v=r1');if(id!==request){dispose(gltf.scene);return;}clearSelection();model?.removeFromParent();dispose(model);model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(model);const building=model.getObjectByName('Architecture_Upper_Proxy');if(building)building.visible=$('full-building').checked;season();fillSelect();$('download-model').href='models/'+file;$('model-caption').textContent=key==='existing'?'现状 · 清理杂物后':`方案 ${key} · 第${year}年 · 生长示意`;$('design-summary').replaceChildren();const b=document.createElement('b'),p=document.createElement('p');b.textContent=summary[key][0];p.textContent=summary[key][1];$('design-summary').append(b,p);$('fallback-plan').src='assets/plan-'+(key==='existing'?'existing':key)+'.svg';$('loading').hidden=true;invalidate();
 }catch(err){if(id!==request)return;console.error(err);$('loading').hidden=true;$('failure').hidden=false;}}
function choose(key){choice=key;loadModel();}
async function start(){[config,plants,layouts]=await Promise.all(['site-config.json','plants.json','layouts.json'].map(async name=>{const r=await fetch('./'+name+'?v=r1');if(!r.ok)throw Error(name+' unavailable');return r.json();}));
 renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=false;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','可旋转的庭院模型；方向键平移，也可用列表选择植物');view.prepend(renderer.domElement);
 scene=new T.Scene();scene.background=new T.Color('#e9eeea');camera=new T.PerspectiveCamera(43,1,.1,160);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=1.3;controls.maxDistance=65;controls.maxPolarAngle=Math.PI*.485;controls.screenSpacePanning=true;controls.addEventListener('change',invalidate);controls.listenToKeyEvents(renderer.domElement);scene.add(new T.HemisphereLight(0xffffff,0x7b7b63,2.2));const sun=new T.DirectionalLight(0xfff5e1,2.6);sun.position.set(30,25,-5);sun.target.position.set(12,0,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-21,right:21,top:21,bottom:-21,near:1,far:80});sun.shadow.bias=-.0004;sun.shadow.normalBias=.025;scene.add(sun,sun.target);
 for(const [key,label,pos]of [['zone1','01 北院',[3.5,.3,5]],['zone2','02 南院',[21,.2,5]],['passage','03 东侧通道',[12,.4,.9]],['bed1','P1',[2.75,.85,1.07]],['bed2','P2',[2.75,.85,2.63]]]){const el=document.createElement('button');el.className='pin';el.textContent=label;el.onclick=()=>showFeature(key);$('labels').append(el);pins.push({el,key,pos:new T.Vector3(...pos)});}
 let down;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!model||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(model,true).find(h=>{let o=h.object;while(o){if(!o.visible||o.scale.lengthSq()===0)return false;o=o.parent;}return true;});if(hit){let o=hit.object;while(o&&!o.userData.plantGroup&&!o.userData.feature)o=o.parent;if(o)showFeature(o.userData.plantGroup??o.userData.feature);}});
 $('feature-select').onchange=e=>showFeature(e.target.value);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-design]').forEach(b=>b.onclick=()=>choose(b.dataset.design));document.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>{choose(b.dataset.choose);document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'});});$('year').onchange=e=>{year=Number(e.target.value);loadModel();};$('season').onchange=season;$('reset').onclick=()=>setView('all');$('full-building').onchange=e=>{const b=model?.getObjectByName('Architecture_Upper_Proxy');if(b)b.visible=e.target.checked;invalidate();};$('annotations').onchange=invalidate;$('shadows').onchange=e=>{renderer.shadowMap.enabled=e.target.checked;scene.traverse(o=>{if(o.material)o.material.needsUpdate=true;});invalidate();};renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('failure').hidden=false;});new ResizeObserver(resize).observe(view);setView('all');resize();await loadModel();}
start().catch(err=>{console.error(err);$('loading').hidden=true;$('failure').hidden=false;});
